name: aruzi
env_file: ./core.env

services:
  headscale:
    container_name: vpn
    image: headscale/headscale:0.22.3
    volumes:
      - ../etc/headscale:/etc/headscale
      - ../etc/headscale/data:/etc/headscale/data/
    ports:
    - "${HEADSCALE_PORT}:8080"
    command: headscale serve
    restart: unless-stopped
    env_file:
    - ./core.env
    

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" 
    volumes:
      - ../etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../etc/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - ./core.env

  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped

    volumes:
      - ../etc/glance/root/config/glance.yml:/app/config/glance.yml
      - ../etc/glance/root/config/home.yml:/app/config/home.yml
      - ../etc/glance/root/assets:/app/assets
      - ../etc/localtime:/etc/localtime:ro

    # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - ${GLANCE_PORT}:8080
    env_file: ../etc/glance/root/.env

volumes:
  caddy_data:
  caddy_config: